WIDTH = 800
HEIGHT = 600
NUM_PARTICULAS = 100
G = 0.1  # Constante gravitacional simulada
FUSION_DIST = 5  # Distancia a la que se fusionan las partículas
TAMANO_PARTICULA = 7  # Tamaño base de las partículas
MASA_MIN = 5  # Masa mínima de las partículas
MASA_MAX = 15  # Masa máxima de las partículas
RADIO_ESCALA = 0.1  # Puedes ajustarlo para cambiar visualmente el tamaño


# Colores en formato RGB para las partículas
COLOR_MIN = [0, 0, 0]  # Rango mínimo (negro)
COLOR_MAX = [255, 255, 255]  # Rango máximo (blanco)

